import streamlit as st
import io
import zipfile
import time

# ---------------------------------------------------------
# 1. Page Configuration (Website Settings)
# ---------------------------------------------------------
st.set_page_config(
    page_title="AI App Builder Pro",
    page_icon="🚀",
    layout="wide",
    initial_sidebar_state="expanded"
)

# ---------------------------------------------------------
# 2. Session State (Database Simulation)
# ---------------------------------------------------------
if 'logged_in' not in st.session_state:
    st.session_state['logged_in'] = False
if 'username' not in st.session_state:
    st.session_state['username'] = ""
if 'projects' not in st.session_state:
    st.session_state['projects'] = {}

# ---------------------------------------------------------
# 3. AI Code Generation Engine
# ---------------------------------------------------------
def generate_app_code(app_name, theme_color, features, app_type):
    
    # 1. Pubspec.yaml
    dependencies = "  flutter:\n    sdk: flutter\n  cupertino_icons: ^1.0.2"
    
    if "User Login (Firebase)" in features:
        dependencies += "\n  firebase_auth: ^4.2.0"
    if "Google Maps" in features:
        dependencies += "\n  google_maps_flutter: ^2.2.0"
    if "Payment Gateway" in features:
        dependencies += "\n  stripe_payment: ^1.0.0"
    if "Push Notifications" in features:
        dependencies += "\n  firebase_messaging: ^13.0.0"

    pubspec_content = f"""name: {app_name.lower().replace(" ", "_")}
description: Professional {app_type} app generated by AI.
version: 1.0.0+1
environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
{dependencies}

flutter:
  uses-material-design: true
"""

    # 2. Main.dart
    feature_widgets = ""
    if "User Login (Firebase)" in features:
        feature_widgets += "\n            ElevatedButton(onPressed: (){}, child: Text('Login with Email')),"
    if "Google Maps" in features:
        feature_widgets += "\n            Container(height: 200, color: Colors.grey[300], child: Center(child: Text('Map Integration Here'))),"
    
    main_dart_content = f"""
import 'package:flutter/material.dart';

void main() {{
  runApp(const MyApp());
}}

class MyApp extends StatelessWidget {{
  const MyApp({{super.key}});

  @override
  Widget build(BuildContext context) {{
    return MaterialApp(
      title: '{app_name}',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.{theme_color.lower()},
        useMaterial3: true,
      ),
      home: const HomeScreen(),
    );
  }}
}}

class HomeScreen extends StatelessWidget {{
  const HomeScreen({{super.key}});

  @override
  Widget build(BuildContext context) {{
    return Scaffold(
      appBar: AppBar(
        title: const Text('{app_name}'),
        backgroundColor: Colors.{theme_color.lower()},
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(20),
        child: Column(
          children: [
            const Text(
              'Welcome to {app_name}',
              style: TextStyle(fontSize: 28, fontWeight: FontWeight.bold),
            ),
            const SizedBox(height: 30),
            {feature_widgets}
            const SizedBox(height: 20),
            const Card(
              child: Padding(
                padding: EdgeInsets.all(16),
                child: Text("App Dashboard"),
              ),
            )
          ],
        ),
      ),
    );
  }}
}}
"""
    return {"pubspec.yaml": pubspec_content, "lib/main.dart": main_dart_content}

def get_zip_download(files):
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as zip_file:
        for name, data in files.items():
            zip_file.writestr(name, data)
    return buffer.getvalue()

# ---------------------------------------------------------
# 4. UI Functions
# ---------------------------------------------------------
def login_screen():
    st.markdown("<h1 style='text-align: center;'>🔐 AI App Builder Pro</h1>", unsafe_allow_html=True)
    col1, col2, col3 = st.columns([1,1,1])
    with col2:
        with st.form("login_form"):
            username = st.text_input("Username")
            password = st.text_input("Password", type="password")
            submitted = st.form_submit_button("Login")
            if submitted:
                if username and password:
                    st.session_state['logged_in'] = True
                    st.session_state['username'] = username
                    st.rerun()
                else:
                    st.error("Please enter credentials.")

def dashboard_screen():
    st.sidebar.title(f"User: {st.session_state['username']}")
    menu = st.sidebar.radio("Menu", ["Create App", "My Apps", "Logout"])
    
    if menu == "Logout":
        st.session_state['logged_in'] = False
        st.rerun()
        
    elif menu == "Create App":
        st.title("🛠️ Create New App")
        with st.form("app_form"):
            app_name = st.text_input("App Name")
            app_type = st.selectbox("Type", ["E-Commerce", "Social", "Business"])
            color = st.selectbox("Color", ["Blue", "Red", "Green"])
            features = st.multiselect("Features", ["User Login (Firebase)", "Google Maps", "Push Notifications"])
            submitted = st.form_submit_button("Generate Code")
            
            if submitted and app_name:
                st.session_state['projects'][app_name] = {"type": app_type, "color": color, "features": features}
                st.success(f"App {app_name} Created!")
                files = generate_app_code(app_name, color, features, app_type)
                zip_data = get_zip_download(files)
                st.download_button("Download ZIP", zip_data, f"{app_name}.zip", "application/zip")

    elif menu == "My Apps":
        st.title("My Projects")
        for name, data in st.session_state['projects'].items():
            st.write(f"📱 **{name}** ({data['type']})")

# ---------------------------------------------------------
# 5. Run App
# ---------------------------------------------------------
if __name__ == "__main__":
    if st.session_state['logged_in']:
        dashboard_screen()
    else:
        login_screen()
              
