import streamlit as st
import io
import zipfile
import time


# ---------------------------------------------------------
# 1. Page Configuration (Website Settings)
# ---------------------------------------------------------
st.set_page_config(
    page_title="AI App Builder Pro",
    page_icon="🚀",
    layout="wide",
    initial_sidebar_state="expanded"
)


# ---------------------------------------------------------
# 2. Session State (Database Simulation)
# ---------------------------------------------------------
# Yeh check karta hai k user login hai ya nahi, aur data save rakhta hai
if 'logged_in' not in st.session_state:
    st.session_state['logged_in'] = False
if 'username' not in st.session_state:
    st.session_state['username'] = ""
if 'projects' not in st.session_state:
    st.session_state['projects'] = {} # Apps ka data yahan save hoga


# ---------------------------------------------------------
# 3. AI Code Generation Engine (Flutter)
# ---------------------------------------------------------
def generate_app_code(app_name, theme_color, features, app_type):
    
    # 1. Pubspec.yaml (Settings File)
    dependencies = " flutter:\n sdk: flutter\n cupertino_icons: ^1.0.2"
    
    # Adding libraries based on features
    if "User Login (Firebase)" in features:
        dependencies += "\n firebase_auth: ^4.2.0"
    if "Google Maps" in features:
        dependencies += "\n google_maps_flutter: ^2.2.0"
    if "Payment Gateway" in features:
        dependencies += "\n stripe_payment: ^1.0.0"
    if "Push Notifications" in features:
        dependencies += "\n firebase_messaging: ^13.0.0"


    pubspec_content = f"""name: {app_name.lower().replace(" ", "_")}
description: Professional {app_type} app generated by AI.
version: 1.0.0+1
environment:
  sdk: ">=2.18.0 <4.0.0"


dependencies:
{dependencies}


flutter:
  uses-material-design: true
"""


    # 2. Main.dart (App UI Code)
    feature_widgets = ""
    if "User Login (Firebase)" in features:
        feature_widgets += "\n ElevatedButton(onPressed: (){}, child: Text('Login with Email')),"
    if "Google Maps" in features:
        feature_widgets += "\n Container(height: 200, color: Colors.grey[300], child: Center(child: Text('Map Integration Here'))),"
    
    main_dart_content = f"""
import 'package:flutter/material.dart';


void main() {{
  runApp(const MyApp());
}}


class MyApp extends StatelessWidget {{
  const MyApp({{super.key}});


  @override
  Widget build(BuildContext context) {{
    return MaterialApp(
      title: '{app_name}',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.{theme_color.lower()},
        useMaterial3: true,
      ),
      home: const HomeScreen(),
    );
  }}
}}


class HomeScreen extends StatelessWidget {{
  const HomeScreen({{super.key}});


  @override
  Widget build(BuildContext context) {{
    return Scaffold(
      appBar: AppBar(
        title: const Text('{app_name}'),
        backgroundColor: Colors.{theme_color.lower()},
        actions: [
          IconButton(icon: const Icon(Icons.notifications), onPressed: () {{}}),
        ],
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(20),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            const Text(
              'Welcome to {app_name}',
              style: TextStyle(fontSize: 28, fontWeight: FontWeight.bold),
              textAlign: TextAlign.center,
            ),
            const SizedBox(height: 10),
            const Text(
              'This is a premium {app_type} Application created via AI Tool.',
              textAlign: TextAlign.center,
              style: TextStyle(color: Colors.grey),
            ),
            const SizedBox(height: 30),
            {feature_widgets}
            const SizedBox(height: 20),
            Card(
              elevation: 4,
              child: Padding(
                padding: EdgeInsets.all(16),
                child: Column(
                  children: [
                    Icon(Icons.app_settings_alt, size: 50, color: Colors.{theme_color.lower()}),
                    SizedBox(height: 10),
                    Text("Dashboard Feature"),
                  ],
                ),
              ),
            )
          ],
        ),
      ),
      bottomNavigationBar: BottomNavigationBar(
        items: const [
          BottomNavigationBarItem(icon: Icon(Icons.home), label: "Home"),
          BottomNavigationBarItem(icon: Icon(Icons.person), label: "Profile"),
        ],
      ),
    );
  }}
}}
"""
    return {"pubspec.yaml": pubspec_content, "lib/main.dart": main_dart_content}


def get_zip_download(files):
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as zip_file:
        for name, data in files.items():
            zip_file.writestr(name, data)
    return buffer.getvalue()


# ---------------------------------------------------------
# 4. UI Functions (Pages)
# ---------------------------------------------------------


def login_screen():
    st.markdown("<h1 style='text-align: center;'>🔐 AI App Builder Login</h1>", unsafe_allow_html=True)
    st.markdown("<p style='text-align: center;'>Create Android & iOS Apps in Minutes</p>", unsafe_allow_html=True)
    
    col1, col2, col3 = st.columns([1,1,1])
    with col2:
        with st.form("login_form"):
            st.write("### Login to Dashboard")
            username = st.text_input("Username")
            password = st.text_input("Password", type="password")
            submitted = st.form_submit_button("Login Now")
            
            if submitted:
                if username and password:
                    st.session_state['logged_in'] = True
                    st.session_state['username'] = username
                    st.success("Login Successful!")
                    time.sleep(1)
                    st.rerun()
                else:
                    st.error("Please enter credentials.")


def dashboard_screen():
    # Sidebar
    st.sidebar.image("https://cdn-icons-png.flaticon.com/512/4712/4712035.png", width=100)
    st.sidebar.title(f"Hello, {st.session_state['username']}")
    menu = st.sidebar.radio("Navigation", ["Create New App", "My Apps", "Settings", "Logout"])
    
    if menu == "Logout":
        st.session_state['logged_in'] = False
        st.rerun()
        
    elif menu == "Create New App":
        st.title("🛠️ Create Professional App")
        st.write("Fill in the details below, and our AI will write the code for you.")
        
        with st.form("app_creation_form"):
            col1, col2 = st.columns(2)
            with col1:
                app_name = st.text_input("App Name", placeholder="e.g. Dream Store")
                app_type = st.selectbox("Category", ["E-Commerce", "Social Media", "Education", "Health & Fitness", "Booking System"])
            with col2:
                theme_color = st.selectbox("Primary Theme Color", ["Blue", "Red", "Green", "Purple", "Orange", "Teal"])
                platform = st.multiselect("Platforms", ["Android", "iOS"], default=["Android", "iOS"])
            
            st.markdown("### ⚡ Advanced Features")
            features = st.multiselect(
                "Select features to include:",
                ["User Login (Firebase)", "Push Notifications", "Google Maps", "Payment Gateway", "Chat System", "Dark Mode"],
                default=["User Login (Firebase)"]
            )
            
            submitted = st.form_submit_button("🚀 Generate App Code")
            
            if submitted and app_name:
                with st.spinner("AI is analyzing requirements..."):
                    time.sleep(1)
                with st.spinner("Writing Flutter Code for Android & iOS..."):
                    time.sleep(1.5)
                
                # Save to Session State
                st.session_state['projects'][app_name] = {
                    "type": app_type,
                    "color": theme_color,
                    "features": features,
                    "date": time.strftime("%Y-%m-%d")
                }
                
                st.success(f"🎉 App '{app_name}' created successfully!")
                
                # Generate Code
                code_files = generate_app_code(app_name, theme_color, features, app_type)
                zip_file = get_zip_download(code_files)
                
                st.download_button(
                    label="📥 Download Source Code (ZIP)",
                    data=zip_file,
                    file_name=f"{app_name}_source_code.zip",
                    mime="application/zip"
                )
    
    elif menu == "My Apps":
        st.title("📱 Your Projects")
        if not st.session_state['projects']:
            st.info("No apps created yet. Go to 'Create New App'.")
        else:
            for name, details in st.session_state['projects'].items():
                with st.expander(f"📲 {name} ({details['type']}) - {details['date']}"):
                    st.write(f"**Theme:** {details['color']}")
                    st.write(f"**Features:** {', '.join(details['features'])}")
                    
                    c1, c2 = st.columns([1, 4])
                    with c1:
                        # Re-download logic
                        code_files = generate_app_code(name, details['color'], details['features'], details['type'])
                        zip_file = get_zip_download(code_files)
                        st.download_button("📥 Download", data=zip_file, file_name=f"{name}.zip", key=name)
                    with c2:
                        st.button(f"✏️ Edit App", key=f"edit_{name}", help="Feature coming soon in Pro version")


# ---------------------------------------------------------
# 5. Main Execution
# ---------------------------------------------------------
if __name__ == "__main__":
    if st.session_state['logged_in']:
        dashboard_screen()
    else:
        login_screen()

