import streamlit as st
import io
import zipfile
import time

# ---------------------------------------------------------
# 1. Page Configuration
# ---------------------------------------------------------
st.set_page_config(
    page_title="AI App Builder Pro",
    page_icon="🚀",
    layout="wide",
    initial_sidebar_state="expanded"
)

# ---------------------------------------------------------
# 2. Session State Setup
# ---------------------------------------------------------
if 'logged_in' not in st.session_state:
    st.session_state['logged_in'] = False
if 'username' not in st.session_state:
    st.session_state['username'] = ""
if 'projects' not in st.session_state:
    st.session_state['projects'] = {}

# New variables to handle download outside the form
if 'last_generated_zip' not in st.session_state:
    st.session_state['last_generated_zip'] = None
if 'last_app_name' not in st.session_state:
    st.session_state['last_app_name'] = ""

# ---------------------------------------------------------
# 3. Code Generation Logic
# ---------------------------------------------------------
def generate_app_code(app_name, theme_color, features, app_type):
    # 1. Pubspec.yaml
    dependencies = "  flutter:\n    sdk: flutter\n  cupertino_icons: ^1.0.2"
    
    if "User Login (Firebase)" in features:
        dependencies += "\n  firebase_auth: ^4.2.0"
    if "Google Maps" in features:
        dependencies += "\n  google_maps_flutter: ^2.2.0"
    if "Payment Gateway" in features:
        dependencies += "\n  stripe_payment: ^1.0.0"
    
    pubspec_content = f"""name: {app_name.lower().replace(" ", "_")}
description: {app_type} app generated by AI.
version: 1.0.0+1
environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
{dependencies}

flutter:
  uses-material-design: true
"""

    # 2. Main.dart
    main_dart_content = f"""
import 'package:flutter/material.dart';

void main() {{
  runApp(const MyApp());
}}

class MyApp extends StatelessWidget {{
  const MyApp({{super.key}});

  @override
  Widget build(BuildContext context) {{
    return MaterialApp(
      title: '{app_name}',
      theme: ThemeData(
        primarySwatch: Colors.{theme_color.lower()},
      ),
      home: Scaffold(
        appBar: AppBar(title: const Text('{app_name}')),
        body: Center(child: Text('Welcome to {app_name}')),
      ),
    );
  }}
}}
"""
    return {"pubspec.yaml": pubspec_content, "lib/main.dart": main_dart_content}

def get_zip_download(files):
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as zip_file:
        for name, data in files.items():
            zip_file.writestr(name, data)
    return buffer.getvalue()

# ---------------------------------------------------------
# 4. UI Screens
# ---------------------------------------------------------
def login_screen():
    st.markdown("<h1 style='text-align: center;'>🔐 AI App Builder Pro</h1>", unsafe_allow_html=True)
    col1, col2, col3 = st.columns([1,1,1])
    with col2:
        with st.form("login_form"):
            username = st.text_input("Username")
            password = st.text_input("Password", type="password")
            submitted = st.form_submit_button("Login")
            if submitted:
                if username and password:
                    st.session_state['logged_in'] = True
                    st.session_state['username'] = username
                    st.rerun()
                else:
                    st.error("Enter username and password.")

def dashboard_screen():
    st.sidebar.title(f"User: {st.session_state['username']}")
    menu = st.sidebar.radio("Menu", ["Create App", "My Apps", "Logout"])
    
    if menu == "Logout":
        st.session_state['logged_in'] = False
        st.rerun()
        
    elif menu == "Create App":
        st.title("🛠️ Create New App")
        
        # --- FORM START ---
        with st.form("app_form"):
            app_name = st.text_input("App Name")
            app_type = st.selectbox("Type", ["E-Commerce", "Social", "Business"])
            color = st.selectbox("Color", ["Blue", "Red", "Green"])
            features = st.multiselect("Features", ["User Login (Firebase)", "Google Maps", "Push Notifications"])
            
            # Submit Button
            submitted = st.form_submit_button("Generate Code")
            
            if submitted and app_name:
                # 1. Save app data
                st.session_state['projects'][app_name] = {"type": app_type, "color": color, "features": features}
                
                # 2. Generate ZIP
                files = generate_app_code(app_name, color, features, app_type)
                zip_data = get_zip_download(files)
                
                # 3. Save ZIP to session state (NOT displaying button here)
                st.session_state['last_generated_zip'] = zip_data
                st.session_state['last_app_name'] = app_name
                
                st.success(f"App '{app_name}' generated! Download button is below.")
        # --- FORM END ---

        # --- DOWNLOAD BUTTON (Outside Form) ---
        if st.session_state['last_generated_zip'] is not None:
            st.write("---")
            st.subheader("⬇️ Download Your App")
            st.download_button(
                label=f"Download {st.session_state['last_app_name']} Code (ZIP)",
                data=st.session_state['last_generated_zip'],
                file_name=f"{st.session_state['last_app_name']}.zip",
                mime="application/zip"
            )

    elif menu == "My Apps":
        st.title("My Projects")
        if not st.session_state['projects']:
            st.info("No apps created yet.")
        else:
            for name, data in st.session_state['projects'].items():
                st.write(f"📱 **{name}** - {data['type']}")

# ---------------------------------------------------------
# 5. Main Run
# ---------------------------------------------------------
if __name__ == "__main__":
    if st.session_state['logged_in']:
        dashboard_screen()
    else:
        login_screen()
        
